-- Whispering Willow complete database setup

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null,
  price numeric not null default 0,
  description text not null default '',
  image text not null default '/placeholder.svg',
  created_at timestamptz not null default now()
);

alter table products add column if not exists is_active boolean not null default true;
alter table products alter column price type numeric using regexp_replace(price::text, '[^0-9.]', '', 'g')::numeric;

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_number text unique default ('WW-' || upper(substr(md5(random()::text), 1, 8))),
  customer_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  payment_method text not null check (payment_method in ('cod', 'bank_transfer')),
  transaction_reference text,
  proof_url text,
  notes text,
  admin_notes text,
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  discount_code text,
  delivery_charge numeric not null default 250,
  total numeric not null check (total >= 0),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'processing', 'shipped', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

alter table orders add column if not exists user_id uuid references auth.users(id);
alter table orders add column if not exists subtotal numeric not null default 0;
alter table orders add column if not exists discount numeric not null default 0;
alter table orders add column if not exists discount_code text;
alter table orders add column if not exists delivery_charge numeric not null default 250;

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint,
  name text not null,
  price numeric not null,
  quantity integer not null check (quantity > 0),
  total numeric not null check (total >= 0)
);

create table if not exists store_settings (
  id boolean primary key default true,
  bank_name text not null default '',
  bank_account_name text not null default '',
  bank_account_number text not null default '',
  contact_email text not null default '',
  contact_phone text not null default '',
  instagram_url text not null default '',
  checkout_note text not null default '',
  updated_at timestamptz not null default now()
);

insert into store_settings (id) values (true) on conflict (id) do nothing;

create table if not exists discount_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  value numeric not null check (value > 0),
  is_active boolean not null default true,
  expires_at timestamptz,
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  usage_count integer not null default 0,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('order-proofs', 'order-proofs', true)
on conflict (id) do nothing;