alter table orders add column if not exists subtotal numeric not null default 0;
alter table orders add column if not exists discount numeric not null default 0;
alter table orders add column if not exists delivery_charge numeric not null default 250;
alter table orders add column if not exists discount_code text;

create table if not exists discount_codes (
	id bigint generated by default as identity primary key,
	code text not null unique,
	discount_type text not null check (discount_type in ('percentage', 'fixed')),
	value numeric not null check (value > 0),
	is_active boolean not null default true,
	expires_at timestamptz,
	usage_limit integer check (usage_limit is null or usage_limit > 0),
	usage_count integer not null default 0,
	created_at timestamptz not null default now()
);